#!/bin/bash

while true
do
    time=$(date +%s)
    expiry=$(cat /etc/deathstamp)

    if [[ $expiry -lt $time ]]
    then
        echo "Deleting instance '$(hostname)' and imploding..."
        id=$(curl -s http://169.254.169.254/metadata/v1/id)
        /bin/su op -c "/snap/bin/doctl compute droplet delete $id -f"
    else
        seconds_to_death=$(expr $(cat /etc/deathstamp) - $(date +%s))
        echo "Seconds left until expiry: $seconds_to_death"
    fi
    sleep 10
done
