#!/bin/bash

notified_10=false
notified_1=false

while true
do
    time=$(date +%s)
    expiry=$(cat /etc/deathstamp)

    if [[ $expiry -lt $time ]]
    then
        echo "Deleting instance '$(hostname)' and imploding..."
        id=$(curl -s http://169.254.169.254/metadata/v1/id)
        /bin/su op -c "/snap/bin/doctl compute droplet delete $id -f"
    else
        seconds_to_death=$(expr $(cat /etc/deathstamp) - $(date +%s))
        echo "Seconds left until expiry: $seconds_to_death"
    	if [[ $seconds_to_death -lt 600 && "$notified_10" == "false" ]]
    	then
	    /home/op/bin/telegram "Instance: '$(hostname)' will expire in 10 minutes\!"
    	notified_10=true
	fi

	if [[ $seconds_to_death -lt 30 && "$notified_1" == "false" ]]
	then
	    /home/op/bin/telegram "Instance: '$(hostname)' self destructing in 30 seconds\!"
    	notified_1=true
	fi
    fi
    sleep 5
done
